### ISSUE TITLE
Panic when running simple test

### ISSUE THREAD

**Issue by wouterb** [Djuke/httpapitester#2]
I try to use this project with a simple testsuite:

``` json
{
  "default":{
    "request":{
      "url":{
        "scheme":"http",
        "host":"google.com"
      }
    },
    "printDebugOnFail":true
  },
  "first":[
    {
      "label":"index",
      "request":{
        "method":"GET",
        "url":{
          "path":"/"
        }
      },
      "response":{
        "statusCode":200,
        "bodyCheck":false
      }
    }
  ]
}
```

But i get a panic:

```
v2.1.0
Executed 0 of 1panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x18 pc=0x403d08]

goroutine 1 [running]:
main.(*Test).prepareHeaders(0xc820010640, 0x0)
    /go/src/test.go:181 +0x3c8
main.(*Test).Prepare(0xc820010640, 0x0)
    /go/src/test.go:118 +0x390
main.(*TestSuite).Run(0xc82008a240)
    /go/src/testsuite.go:31 +0x458
main.main()
    /go/src/main.go:29 +0x3f9

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:1696 +0x1
```

**Comment by Djuke** [comment]
fixed 9faae589c9a943e7319fa084ca471083f0773735
